version: '3.8'

services:
  sql-introduction:
    image: mysql:8.0
    container_name: sql-introduction
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sql-introduction
      MYSQL_USER: fer
      MYSQL_PASSWORD: ferpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./:/sql-introduction-scripts
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      retries: 5

volumes:
  mysql_data:


