services:
  sql-introduction:
    image: mysql:8.0
    restart: always
    container_name: sql-introduction
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./:/sql-introduction-scripts

volumes:
  mysql_data:
